# Generated by Django 4.1.4 on 2022-12-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('url_github', models.CharField(max_length=100)),
            ],
        ),
    ]
