# Generated by Django 4.1.4 on 2022-12-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(max_length=200),
        ),
    ]
