# Generated by Django 4.1.4 on 2022-12-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='photo',
            new_name='url_photo',
        ),
    ]
