# Generated by Django 4.1.4 on 2022-12-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_photo_formdata_url_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formdata',
            table='formulario_proyecto',
        ),
    ]
